title: rand(thoughts)
description: Random thoughts and rants about things I barely understand
author: Guillaume Malette
github: https://github.com/gmalette
about: I'm a web developer by day, struggling to understand Ruby.
disqus_shortname:
google_analytics: UA-131111846-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/gmalette"
    - icon: fa-github
      link: "https://github.com/gmalette"

share:
  twitter_username: gmalette

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://gmalette.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
