title: "Guillaume's Horrible Code-Along Blog"
description: "Random thoughts and rants about things I strive understand"
author: "Guillaume Malette"
github: "https://github.com/gmalette"
about: "I'm a web developer by day, trying to understand Ruby."
disqus_shortname:
google_analytics: "UA-131111846-1"
avatar_url: "https://gravatar.com/avatar/944e45061dc58d6d996c2b605cce6c09?s=150"

enableTags: true
tagarray: []

social:
  - icon: "fa-twitter"
    link: "https://twitter.com/gmalette"
  - icon: "fa-github"
    link: "https://github.com/gmalette"

share:
  twitter_username: "gmalette"

urls:
  - text: "Blog Repo"
    url: "https://github.com/gmalette/gmalette.github.io"
  - text: "XML Feed"
    url: "/feed.xml"
  - text: "Subscribe"
    url: "https://github.com/gmalette/gmalette.github.io#subscribe"

url: "https://gmalette.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: "kramdown"
highlighter: "rouge"
plugins:
  - "jekyll-paginate"
  - "jekyll-gist"
  - "rouge"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
